// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Jobstatus string

const (
	JobstatusWishlist  Jobstatus = "wishlist"
	JobstatusDrafting  Jobstatus = "drafting"
	JobstatusApplied   Jobstatus = "applied"
	JobstatusFollowUp  Jobstatus = "follow_up"
	JobstatusScreening Jobstatus = "screening"
	JobstatusTechnical Jobstatus = "technical"
	JobstatusFinal     Jobstatus = "final"
	JobstatusOffer     Jobstatus = "offer"
	JobstatusRejected  Jobstatus = "rejected"
	JobstatusGhosted   Jobstatus = "ghosted"
)

func (e *Jobstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Jobstatus(s)
	case string:
		*e = Jobstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Jobstatus: %T", src)
	}
	return nil
}

type NullJobstatus struct {
	Jobstatus Jobstatus
	Valid     bool // Valid is true if Jobstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Jobstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Jobstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Jobstatus), nil
}

type Job struct {
	ID          int32
	Company     string
	Role        string
	Url         pgtype.Text
	Description pgtype.Text
	Status      NullJobstatus
	CreatedAt   pgtype.Timestamp
	AppliedAt   pgtype.Timestamp
}
