// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (company, role, url, description, status) VALUES ($1, $2, $3, $4, $5) RETURNING id, company, role, url, description, status, created_at, applied_at
`

type CreateJobParams struct {
	Company     string
	Role        string
	Url         pgtype.Text
	Description pgtype.Text
	Status      NullJobstatus
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Company,
		arg.Role,
		arg.Url,
		arg.Description,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Url,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, company, role, url, description, status, created_at, applied_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int32) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Url,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, company, role, url, description, status, created_at, applied_at FROM jobs
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.Url,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET company = $2, role = $3, url = $4, description = $5, status = $6 WHERE id = $1 RETURNING id, company, role, url, description, status, created_at, applied_at
`

type UpdateJobParams struct {
	ID          int32
	Company     string
	Role        string
	Url         pgtype.Text
	Description pgtype.Text
	Status      NullJobstatus
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Company,
		arg.Role,
		arg.Url,
		arg.Description,
		arg.Status,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Url,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}
